behaviors:
  RaceAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256 # Increased batch size
      buffer_size: 5120 # Increased buffer size
      learning_rate: 2.5e-4 # Adjusted learning rate
      beta: 1.0e-3 # Adjusted beta
      epsilon: 0.15 # Adjusted epsilon
      lambd: 0.95
      num_epoch: 10 # Increased number of epochs
    network_settings:
      normalize: true
      hidden_units: 256 # Increased hidden units for potentially better learning
      num_layers: 3 # Increased number of layers
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.01 # Added curiosity reward signal
        gamma: 0.99
    max_steps: 1.0e6 # Increased max steps
    time_horizon: 128 # Increased time horizon
    summary_freq: 10000 # Adjusted summary frequency for less frequent updates
